paketo-buildpacks/dep-server

pkg/dependency/yarn.go
pkg/dependency/yarn_test.go

Remove 'v' from yarn versions

---

pkg/dependency/yarn.go
pkg/dependency/yarn_test.go

Fix asset error when obtaining yarn version

Fix asset error when obtaining yarn version

---

.github/workflows/auto-approve.yml
.github/workflows/auto-merge.yml
.github/workflows/generate-dependency-workflows.yml

Swtich to Paketo-bot and uses PRs instead of commiting directly

Swtich to Paketo-bot and uses PRs instead of commiting directly

---

.github/workflows/generate-dependency-workflows.yml

Fixes [failing job](https://github.com/paketo-buildpacks/dep-server/actions/runs/611150239)

Remove persist-credentials from checkout

---

.github/workflows/generate-dependency-workflows.yml

Fixes [failing workflow](https://github.com/paketo-buildpacks/dep-server/runs/2007191547?check_suite_focus=true#step:11:7)

Checkout code with token in generate-dependency-workflows.yml

---

.github/data/dependencies.yml
actions/test-dependency/dependency-tests/rust/fixtures/main.rs
actions/test-dependency/dependency-tests/rust/run
go.sum
pkg/dependency/dep_factory.go
pkg/dependency/dependencyfakes/fake_github_client.go
pkg/dependency/internal/github_client.go
pkg/dependency/internal/github_client_test.go
pkg/dependency/rust.go
pkg/dependency/rust_test.go
pkg/dependency/test/acceptance/acceptance_test.go
pkg/dependency/test/acceptance/go.sum

Adds rust to dependency library and dependency workflows
Resolves #1

Add rust to dep-server

---

.github/templates/build-upload.yml
.github/workflows/test-and-deploy-server.yml
.github/workflows/test-dependency-library.yml
actions/get-upstream-dependency/entrypoint/go.mod
actions/list-new-upstream-dependency-versions/entrypoint/go.mod
go.mod
pkg/dependency/test/acceptance/go.mod

Bump Go to go1.16

---

actions/test-dependency/dependency-tests/rust/run

Fixes [failing test](https://github.com/paketo-buildpacks/dep-server/runs/2143754997?check_suite_focus=true)

Fix typo in rust tests

---

README.md

Update README with new deps and updated example

---

actions/test-dependency/dependency-tests/pip/run

Helping to resolve: https://github.com/paketo-community/pip/issues/111

Update pip test to properly consume new pip bundle

---

actions/test-dependency/dependency-tests/pip/run

Update test to properly extract pip

---

actions/upload-metadata/action.yml

Reverts change made in #75 which did not have the expected results.

Revert EOF removal 

---

actions/upload-metadata/action.yml

Fixes the trailing comma in metadata JSON

---

.github/templates/test-upload-metadata.yml

The variable for the `purl` field was incorrect, causing the `purl` field to be empty when uploading metadata to the dep-server. This fixes the variable.

remove outputs from purl client payload string

---

.github/workflows/auto-update-go-sum.yml

Add Setup Go 1.16 step to auto-update-go-sum workflow

Add Setup Go 1.16 step to auto-update-go-sum workflow

---

actions/upload-metadata/action.yml
pkg/dependency/purl/purl.go
pkg/dependency/purl/purl_test.go

Unescape purls. Please ensure that the logic behind unescaping feels sound before merging and feel free to ask any questions.

Fix purl upload

---

actions/upload-metadata/action.yml

fix purl variable

---

actions/get-upstream-dependency/entrypoint/go.sum
actions/list-new-upstream-dependency-versions/entrypoint/go.sum
pkg/dependency/test/acceptance/go.sum

Testing go.sum bump since tests are failing

---

.gitignore
scripts/cyclonedx-node-module.sh

Adds script to generate cyclonedx bom cli artifact

---

.github/workflows/go-test-upload-metadata.yml

Wrong path to the convert-semver action

fix convert-semver action call

---

.github/templates/get-new-versions.yml

We have been experiencing major slow downs in our GHA in which jobs get queued up/scheduled for hours. This PR decreases the frequency that this workflow will run from every 15 minutes to every hour.
cc @dmikusa-pivotal

Decrease cron job timing in new version workflow

---

pkg/dependency/php.go
pkg/dependency/php_test.go

Modifies deprecation date calculations and release date lookup to rely on the minor version line (x.x.*) rather than the patch version. This is because deprecation dates should be calculated based off of the version line release date, not the date the patch was released.
I will go in separately and update the deprecation dates for all versions already in the dependency server metadata. This code change will take effect when new versions of PHP come out.
This PR makes a quick fix for the purposes of fixing PHP. It's highly likely that other dependencies may have wrong deprecation dates for the same reason. A better long term solution would be to look into this repo-wide. Issue #132 has been opened to address this issue on a larger scale in an effort.

PHP: use minor version line to calculate deprecation date

---

actions/test-dependency/dependency-tests/php/fixtures/8-1/expected-modules.txt

Fixes failures associated with the PHP 8.1 tests that are still occurring: https://github.com/paketo-buildpacks/dep-server/runs/5185808532?check_suite_focus=true

add gd to php 8.1 expected modules

---

README.md

Add poetry to README

---

pkg/dependency/composer.go
pkg/dependency/composer_test.go

Adds composer CPE

---

.github/workflows/generate-dependency-workflows.yml

`yj` releases now have the architecture attached.

add architecture to yj tool installation URI

---

.github/templates/get-new-versions.yml

Adds a workflow step to file an issue if the Get New Versions workflow step fails. Once this has been rolled out and we have observed it working, I will add the same step for the Build and Test workflows as well.

file issue if get new versions workflow fails

---

.github/data/dependencies.yml

https://github.com/paketo-buildpacks/yarn/issues/242

Add Jammy stack to Yarn dependency

---

.github/data/dependencies.yml

Adds jammy to list of stacks for nginx and httpd

Adds jammy stack to webservers dependencies

---

pkg/dependency/pypi.go
pkg/dependency/pypi_test.go

Will resolve #217, in which tests were failing because a release candidate version got through automation and failed dependency tests.
cc @paketo-buildpacks/python-maintainers

Don't allow RCs in Poetry versions

---

scripts/validate/main.go

In https://github.com/paketo-buildpacks/packit/pull/389/ and https://github.com/paketo-buildpacks/rfcs/pull/251 we are using the new `checksum` fields instead of `sha256` fields, so this change makes sure the validator accounts for these changes.

modify validator to use checksum field
