paketo-buildpacks/dep-server

actions/upload-metadata/action.yml

Adds timestamps to dependency metadata representing the first build as well as the most recent build.
This allows us to track how long it takes us to build dependencies from the time they were released upstream.

Add created_at and modified_at timestamps to dependency metadata

---

pkg/dependency/internal/github_client.go
pkg/dependency/internal/github_client_test.go
pkg/dependency/rust.go
pkg/dependency/rust_test.go
pkg/dependency/test/acceptance/acceptance_test.go

Signed-off-by: Marty Spiewak <mspiewak@pivotal.io>
Gets the tag commit for Rust in order to obtain the release date
Allows the Build to succeed even when target an unofficial release.

Get Rust tag commit instead of release

---

.github/dependabot.yml

Resolves #59 
Should stop workflows from failing on go.sum issues when dependabot updates roll out.

Update action go.mod with dependendabot updates

---

.github/workflows/tini-test-upload-metadata.yml

May alleviate the error in https://github.com/paketo-buildpacks/dep-server/runs/3067591929?check_suite_focus=true in which the licenses variable is an unexpected array. Wrapping it in single quotes should join the whole array as a single item.

Add single quotes around licenses variable so it's not an array

---

actions/upload-metadata/action.yml

The`EOF` present in the metadata to upload is somehow causing the `jq` command on line 83 below to fail as you can see in https://github.com/paketo-buildpacks/dep-server/actions/runs/1031053919. Removing this should make the JSON valid for the command.
* [] I have added an integration test, if necessary.

remove extra EOF from metadata JSON

---

.github/templates/build-upload.yml
.github/workflows/tini-test-upload-metadata.yml
actions/upload-metadata/action.yml

* Adds a step in build-upload to flatten licenses so that we can pass them amongst workflows
* Remove unncessary single quotes from test-upload licenses, because it can be treated like a normal string arg.
* Un-flatten the string of licenses when we upload the license metadata to the dep-server so that the licenses will appear as an array, rather than a comma-separated string

Flatten licenses array in workflows, unflatten into array during upload

---

.github/workflows/auto-update-go-sum.yml
.github/workflows/update-go-sum.yml

When `dependabot` updates a new dependency it does not modify the `go.sum` files under `actions/get-upstream-dependency/entrypoint` and `actions/list-new-upstream-dependency-versions/entrypoint` that reference the `go.mod` in the root of the project so a problem is generated when one of these actions is used.
I create a new Workflow that updates these files when there is a change in the main `go.mod` file.

Add new workflow that updates go.sum files

---

.github/workflows/auto-update-go-sum.yml

Fix typo in cd path.
It should be `cd "${{ github.workspace }}/pkg/dependency/test/acceptance"` instead of cd `"${{ github.workspace }}/pkg/dependency/tests/acceptance"`

Fix typo in cd path

---

.github/workflows/approve-dependabot-pr.yml
.github/workflows/auto-approve.yml
.github/workflows/test-dep-server.yml

The approval step in the workflows here fails on Dependabot PRs ([like this](https://github.com/paketo-buildpacks/dep-server/pull/97/checks?check_run_id=3158350121)) due to a change in GHA token permissions.
This PR adds a separate Dependabot approval workflow like we use for the rest of our repositories in paketo-buildpacks via [github-config](https://github.com/paketo-buildpacks/github-config/blob/main/implementation/.github/workflows/approve-bot-pr.yml).
This step doesn't include @paketo-bot PRs, because there already exists a separate workflow for those PRs which cover a slightly different use case. In this PR I added a check for human/unverified commits to the paketo-bot approval case as well.

Add separate dependabot approval workflow

---

.github/workflows/generate-dependency-workflows.yml

Add GPG keys to Paketo Bot commit so that the commit verification step in our auto-approval workflows will work. This is what we do in our[ github-config commit workflows](https://github.com/paketo-buildpacks/github-config/blob/3d6c03c00634d6bb1f0f6f7c32ee81a91048cd72/.github/workflows/update-tools.yml#L72-L79).
Enable bot PR auto-approval

Add GPG signing keys to paketo-bot commits so they are verified

---

pkg/dependency/bundler.go
pkg/dependency/composer.go
pkg/dependency/curl.go
pkg/dependency/curl_test.go
pkg/dependency/dep_factory.go
pkg/dependency/dotnet.go
pkg/dependency/go.go
pkg/dependency/go_test.go
pkg/dependency/httpd.go
pkg/dependency/icu.go
pkg/dependency/icu_test.go
pkg/dependency/nginx.go
pkg/dependency/node.go
pkg/dependency/node_test.go
pkg/dependency/pecl.go
pkg/dependency/php.go
pkg/dependency/pypi.go
pkg/dependency/pypi_test.go
pkg/dependency/python.go
pkg/dependency/ruby.go
pkg/dependency/rust.go
pkg/dependency/test/acceptance/acceptance_test.go
pkg/dependency/tini.go
pkg/dependency/tini_test.go
pkg/dependency/yarn.go

Resolves part of #53, makes Go and other dependencies have semantic versions in the dep-server metadata. It does not address the part of issue #53 that requests a JSON feed be used for Go. That will be addressed in a separate PR.
This change has notable effects on the following dependencies:`go`, `curl`, `icu`, `node`, `pip`, and `tini`. It makes the output version of the `GetDependencyVersion` function semver-compatible in the dep-server metadata. These are the only dependencies in the dep-server currently that do not have semantic versions.
This PR also includes the same `convertToSemver` step on all other dependencies, but has no effect because all other versions are already semantic versioned, but it's just not enforced.
Once this PR is merged, we should run the `build and upload` …

All versions in dependency metadata should be semver-compliant

---

.github/workflows/go-test-upload-metadata.yml
actions/convert-semver/action.yml
actions/convert-semver/entrypoint/main.go
actions/convert-semver/entrypoint/main_test.go

Testing a theory that we can just convert the version to semver in the workflow before. If this works, I will put in another PR to roll out the changes workflow-wide

Testing a workflow change to convert version to semver right before upload

---

actions/convert-semver/action.yml

This was causing the version to show up as empty instead of a semver.

remove unnecessary jq from semver conversion  action

---

.github/templates/test-upload-metadata.yml
pkg/dependency/bundler.go
pkg/dependency/composer.go
pkg/dependency/curl.go
pkg/dependency/curl_test.go
pkg/dependency/dep_factory.go
pkg/dependency/dotnet.go
pkg/dependency/go.go
pkg/dependency/go_test.go
pkg/dependency/httpd.go
pkg/dependency/icu.go
pkg/dependency/icu_test.go
pkg/dependency/nginx.go
pkg/dependency/node.go
pkg/dependency/node_test.go
pkg/dependency/pecl.go
pkg/dependency/php.go
pkg/dependency/pypi.go
pkg/dependency/pypi_test.go
pkg/dependency/python.go
pkg/dependency/ruby.go
pkg/dependency/rust.go
pkg/dependency/test/acceptance/acceptance_test.go
pkg/dependency/tini.go
pkg/dependency/tini_test.go
pkg/dependency/yarn.go

Resolves the semantic versioning part of #53. This was previously thought to be solved by #55, but that implementation did not work at the acceptance test level (see [this failed workflow run](https://github.com/paketo-buildpacks/dep-server/runs/3365878755?check_suite_focus=true)) because the version at that point needs to match the _actual_ version due to the nature of the tests. The conversion to semVer needs to happen after the tests, because we only care about the version showing up in semVer in the metadata.
This PR does two major things:
1. Adds a semver conversion step to the test-upload workflow. The action was added in a previous commit. This will essentially just convert the dependency version to semantic version right at the end of the full workflow path just for the metadata …

Semver conversion is test-upload workflow

---

.github/templates/get-new-versions.yml

All of our Get New Versions workflows have been failing for days due to pinning to the master branch of the Google Github Actions SDK. Updating where we pin to should alleviate that issue.

use Cloud SDK v0 instead of master

---

pkg/dependency/pypi.go
pkg/dependency/pypi_test.go

We do not have a CPE for Poetry, but we should.
Note: Poetry does not have a true CPE with versions on the NIST website - just a generic versionless CPE.
Also, I did not run the acceptance tests locally before pushing this PR because I wasn't sure what permissions the github token needed.

Add CPE for poetry.

---

pkg/dependency/pypi.go
pkg/dependency/pypi_test.go

Following on from #152 - we realized that we need to add CPEs for the rest of the python tooling (i.e. `pipenv`). Also, we realized there is no reason not to add the version or the `python` specifier.

Generate CPEs for all python tooling.

---

go.mod
go.sum

Bump Golang semantics to 1.18. So we can have all that new Golang goodness.
- https://go.dev/doc/modules/gomod-ref
- https://go.dev/ref/mod#go-mod-file-go
- https://go.dev/doc/go1.17
- https://go.dev/doc/go1.18

Bump golang semantics to 1.18

---

.github/templates/build-upload.yml
.github/templates/get-new-versions.yml

Hopefully will resolve failures in workflows:
```
go: github.com/onsi/gomega@v1.19.0 requires
github.com/onsi/ginkgo/v2@v2.1.3: missing go.sum entry; to add it:
go mod download github.com/onsi/ginkgo/v2
```
This started ocurring when Golang was bumped to v1.18

Bump go version in workflows

---

.github/workflows/go-test-upload-metadata.yml

This PR adds the `jammy` `tiny` stack to `go` - which we have validated with a custom-built jammy tiny stack. There is no readily-available jammy tiny stack for CI or external consumption yet.
See also: https://github.com/paketo-buildpacks/go-dist/pull/402
Signed-off-by: Frankie Gallina-Jones <frankieg@vmware.com>

Add jammy tiny stack support to golang.

---

.github/data/dependencies.yml

Similar to #160 except putting the config in the correct place so the automation picks it up.
Otherwise the next time the automation runs it will erase the newly-added stack from the `go` workflow.
* [] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.

Add jammy tiny stack to go-dist config.

---

.github/workflows/test-dependency-library.yml
pkg/dependency/acceptance/acceptance_test.go
scripts/acceptance.sh
scripts/unit.sh

Split unit and acceptance so they can be run separately, using the `./scripts/<suite>.sh` mechanism that buildpack authors are familiar with

Split unit and acceptance

---

actions/get-upstream-dependency/entrypoint/main.go
pkg/dependency/internal/checksummer.go
pkg/dependency/nginx.go
pkg/dependency/nginx_test.go

NGINX dependency build for 1.22.0 [failed](https://github.com/paketo-buildpacks/dep-server/actions/runs/2378473323) because the 1.22.0 release tarball is signed by a different PGP key than previous releases have been. I added the other PGP keys and clarified the logging.

Add other valid PGP keys to NGINX key validation

---

pkg/dependency/php.go
pkg/dependency/php_test.go

Co-authored-by: Timothy Hitchener <thitchener@pivotal.io>
Related to #149, the PHP.net CDN is blocking the request to `https://www.php.net/releases/index.php?json` which contains the metadata about all the PHP releases. 
The proposed solution uses a [mirror](https://github.com/brayanhenao/php-releases-information) for the metadata, that contains the exact same information provided by PHP. It also requires modifications to the `getRelease()` function to support a different URL and an alternative JSON structure.

Get PHP versions from a mirror instead of php.net

---

.github/workflows/deploy-dep-server.yml

`Deploy Dep Server` [action](https://github.com/paketo-buildpacks/dep-server/actions/workflows/deploy-dep-server.yml) has been failing for almost 3 months due to an update in the action `setup-gcloud` used in the job.

Update setup-gcloud action version in deploy-dep-server.yml workflow

---

.github/templates/build-upload.yml
.github/templates/test-upload-metadata.yml

Adds failure notification workflow steps to the other two workflows for each dependency.

Add failure notification workflow steps to the other workflows

---

.github/data/dependencies.yml
.github/templates/test-upload-metadata.yml
actions/get-compatible-stacks/Dockerfile
actions/get-compatible-stacks/action.yml
actions/get-compatible-stacks/entrypoint/go.mod
actions/get-compatible-stacks/entrypoint/go.sum
actions/get-compatible-stacks/entrypoint/main.go

In the process of trying to [support Jammy Jellyfish in Paketo](https://github.com/paketo-buildpacks/rfcs/blob/da3339d071ffed23c3cd1b374a6bfcefdea7ac70/text/stacks/0004-jammy-jellyfish.md) we need to test whether existing dependencies are compatible with Jammy. I've found that [.NET 3.1 is not compatible with the Jammy Jellyfish](https://github.com/dotnet/core/issues/7038#issuecomment-1110377345), but .NET 6.0 is. For this reason, the `stacks` metadata for .NET dependencies must be more flexible; it must depend on the version of the dependency, not just the ID. I've updated the workflow template data schema and the `test-and-upload-metadata.yml` workflow to support this use case.
While this PR will ultimately generate a diff in all dependencies' `*-test-and-upload-metadata.yml`, it's …

Make stacks metadata for dependencies dependent on version

---

.github/data/dependencies.yml

So the .NET Core buildpack can run on Jammy stacks

Add Jammy stack to ICU

---

.github/data/dependencies.yml

In order for the Go language family buildpack to run on the Jammy Base and Full stacks, the stack ID `io.buildpacks.stacks.jammy` needs to be added to the go dependency.
Since the Jammy Base build image contains a [superset](https://github.com/paketo-buildpacks/jammy-base-stack/blob/f2ae39f99918b407a6c89feaaad5864024982479/stack/stack.toml#L21) of the [packages in the Jammy Tiny build image](https://github.com/paketo-buildpacks/jammy-tiny-stack/blob/main/stack/stack.toml), and both are based on Ubuntu Jammy Jellyfish, I have confidence the go toolchain will work as expected on the Jammy Base/Full stacks.

Add jammy base/full stack support to the go dependency

---

.github/data/dependencies.yml
.github/data/dependency-workflows-config.yml
.github/templates/build-upload.yml
.github/workflows/generate-dependency-workflows.yml

As a part of https://github.com/paketo-buildpacks/dotnet-core/issues/722, the SDK dependency should not be compiled anymore. Instead, it's URI and SHA256 should be the same as the upstream ones.
This PR does two things:
- provides a mechanism to allow dependencies to not be compiled
- marks the .NET SDK dependency as non-compiled.
I have tested the templating behaviour locally.

Allow for dependencies to not be compiled

---

.github/data/dependencies.yml

Fix `pip` and add Jammy to `python`, `pipenv`, and `poetry`.

Add Jammy to Pythonic dependencies

---

actions/build-dependency/Dockerfile
actions/test-dependency/Dockerfile

Resolves permissions-related issues in https://github.com/paketo-buildpacks/dep-server/issues/196 in which compilation fails due to permissions errors. This error also occurs for the Test action, which uses a stack image in its Dockerfile.

manually set uid and gid to 0 for build/test actions

---

.github/data/dependencies.yml

CPython (as built by dep-server) is not Jammy compatible, so let's remove that from the metadata

CPython is not Jammy compatible

---

actions/test-dependency/dependency-tests/dotnet-aspnetcore/run
actions/test-dependency/dependency-tests/dotnet-runtime/run
actions/test-dependency/dependency-tests/dotnet-sdk/run

All 3 .NET dependency tests are failing:
* https://github.com/paketo-buildpacks/dep-server/issues/209
* https://github.com/paketo-buildpacks/dep-server/issues/208
* https://github.com/paketo-buildpacks/dep-server/issues/207
This is because in https://github.com/paketo-buildpacks/dep-server/pull/183/ we started pulling .NET SDK directly from upstream instead of compiling it. The tarball from upstream is not `tar.xz`, but a `tar.gz`, so the untarring code was failing.
This change generalizes the path we look for tar files in when untarring the dependencies in the tests.

untarring SDK from any tar extension type

---

.github/templates/build-upload.yml
.github/templates/get-new-versions.yml
.github/templates/test-upload-metadata.yml
.github/workflows/approve-dependabot-pr.yml
.github/workflows/auto-merge.yml
actions/build-dependency/entrypoint
actions/convert-semver/action.yml
actions/get-compatible-stacks/entrypoint/go.mod
actions/get-compatible-stacks/entrypoint/go.sum
actions/get-compatible-stacks/entrypoint/main.go
actions/get-upstream-dependency/action.yml
actions/list-new-upstream-dependency-versions/action.yml
actions/upload-dependency/action.yml

Use the new way of producing outputs in a github action as the old way is deprecated and will be removed (31st May 2023).
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
See also: https://github.com/paketo-buildpacks/github-config/pull/604
Keep the pipelines alive.

Replace deprecated GHA ::set-output syntax
